package com.altbank.cardsapi.application.exception;

public enum ErrorCode {
    CUSTOMER_ALREADY_EXISTS,
    ACCOUNT_NOT_FOUND,
    CARD_NOT_FOUND,
    ACCOUNT_CANCELLED,
    CARD_INACTIVE,
    PHYSICAL_CARD_NOT_DELIVERED,
    PHYSICAL_CARD_NOT_VALIDATED,
    VIRTUAL_CARD_ALREADY_EXISTS,
    VIRTUAL_CARD_NOT_FOUND,
    CVV_NOT_AVAILABLE,
    WEBHOOK_UNAUTHORIZED
}
